export const designTokens = {
  name: 'Academic Intelligence Interface',
  colors: {
    surface: '#f8f9ff',
    'surface-dim': '#cbdbf5',
    'surface-bright': '#f8f9ff',
    'surface-container-lowest': '#ffffff',
    'surface-container-low': '#eff4ff',
    'surface-container': '#e5eeff',
    'surface-container-high': '#dce9ff',
    'surface-container-highest': '#d3e4fe',
    'on-surface': '#0b1c30',
    'on-surface-variant': '#45464d',
    'inverse-surface': '#213145',
    'inverse-on-surface': '#eaf1ff',
    outline: '#76777d',
    'outline-variant': '#c6c6cd',
    'surface-tint': '#565e74',
    primary: '#000000',
    'on-primary': '#ffffff',
    'primary-container': '#131b2e',
    'on-primary-container': '#7c839b',
    'inverse-primary': '#bec6e0',
    secondary: '#515f74',
    'on-secondary': '#ffffff',
    'secondary-container': '#d5e3fd',
    'on-secondary-container': '#57657b',
    tertiary: '#000000',
    'on-tertiary': '#ffffff',
    'tertiary-container': '#191c1e',
    'on-tertiary-container': '#818486',
    error: '#ba1a1a',
    'on-error': '#ffffff',
    'error-container': '#ffdad6',
    'on-error-container': '#93000a',
    'primary-fixed': '#dae2fd',
    'primary-fixed-dim': '#bec6e0',
    'on-primary-fixed': '#131b2e',
    'on-primary-fixed-variant': '#3f465c',
    'secondary-fixed': '#d5e3fd',
    'secondary-fixed-dim': '#b9c7e0',
    'on-secondary-fixed': '#0d1c2f',
    'on-secondary-fixed-variant': '#3a485c',
    'tertiary-fixed': '#e0e3e5',
    'tertiary-fixed-dim': '#c4c7c9',
    'on-tertiary-fixed': '#191c1e',
    'on-tertiary-fixed-variant': '#444749',
    background: '#f8f9ff',
    'on-background': '#0b1c30',
    'surface-variant': '#d3e4fe',
  },
} as const;

export const applyDesignTokens = (): void => {
  const root = document.documentElement;
  Object.entries(designTokens.colors).forEach(([token, value]) => {
    root.style.setProperty(`--${token}`, value);
  });
};
